//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComments
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Date { get; set; }
        public int BlogId { get; set; }
        public int MemberId { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Members Members { get; set; }
    }
}
