//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int PriceId { get; set; }
        public bool IsChecked { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<bool> CanComment { get; set; }
        public Nullable<bool> DidPay { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Prices Prices { get; set; }
    }
}
